Web_Programming_With_Python_And_JavaScript/Project04_Network/network/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("create_post", views.create_post, name="create_post"),
    path("profile/<str:username>", views.profile_page, name="profile_page"),
    path("profile/<str:username>/following", views.following_page, {'follow_type': 'following'}, name="following"),
    path("profile/<str:username>/followers", views.following_page, {'follow_type': 'followers'}, name="followers"),

    path("follow", views.follow, name="follow"),
    path("like/<str:post_id>", views.like, name="like"),

    path("edit_post", views.edit_post, name="edit_post")

]

Web_Programming_With_Python_And_JavaScript/Project04_Network/project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Like(models.Model):
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    liked_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Follow(models.Model):
    id = models.AutoField(primary_key=True)
    follow_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follow_from')
    follow_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follow_to')
    created_at = models.DateTimeField(auto_now_add=True)

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import json


from django.contrib import messages

from .models import User, Post, Follow, Like


@login_required
def create_post(request):
    post_text = request.POST.get("text")
    if not post_text:
        messages.error(request, "The post text cannot be empty")

    Post.objects.create(author=request.user, text=post_text)

    messages.info(request, "Successfully created a post")

    return redirect(reverse("index"))

def following_page(request, username, follow_type):
    users = None
    user = User.objects.get(username=username)

    if follow_type == "following":
        users = Follow.objects.filter(follow_from=user.id)
    else:
        users = Follow.objects.filter(follow_to=user.id)

    return render(request, "network/following.html", {
        "users": users,
        "page_type": follow_type
    })


@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    has_already_liked = Like.objects.filter(post=post, liked_by=request.user).exists()

    if has_already_liked:
        Like.objects.filter(post=post, liked_by=request.user).delete()
    else:
        Like.objects.create(post=post, liked_by=request.user)

    return redirect(request.META.get('HTTP_REFERER', reverse('index')))

@login_required
def follow(request):
    if request.method == "POST":
        uid = request.POST.get("user_id")
        user_to_follow = get_object_or_404(User, id=uid)
        already_followed = Follow.objects.filter(follow_from=request.user, follow_to=user_to_follow).exists()

        if already_followed:
            Follow.objects.filter(follow_from=request.user, follow_to=user_to_follow).delete()
            messages.success(request, f"You have unfollowed {user_to_follow.username}.")
        else:
            Follow.objects.create(follow_from=request.user, follow_to=user_to_follow)
            messages.success(request, f"You are now following {user_to_follow.username}.")

        return redirect(request.META.get('HTTP_REFERER', reverse('index')))
    else:
        messages.error(request, "Invalid request method.")
        return HttpResponseRedirect("/", status=405)

@csrf_exempt
def edit_post(request):
    if request.method != "PUT":
        return HttpResponse("Method Not Allowed", status=405)

    json_data = json.loads(request.body.decode('utf-8'))
   
    post_id = json_data.get("postId")
    text = json_data.get("text")

    found_post = get_object_or_404(Post, id=int(post_id))
    
    found_post.text = text
    found_post.save()

    return HttpResponse("Updated successfully!", status=200)

def profile_page(request, username):
    current_user = get_object_or_404(User, username=username)
    user_posts = Post.objects.filter(author=current_user).order_by("-created_at")
    following_count = followers_count = 0

    if request.user.is_authenticated:
        following_count = Follow.objects.filter(follow_from=request.user).count()
        followers_count = Follow.objects.filter(follow_to=request.user).count()
        following = Follow.objects.filter(follow_from=request.user, follow_to=current_user).exists()

    return render(request, "network/profile.html", {
        "current_user": current_user,
        "following": following,
        "following_count": following_count,
        "followers_count": followers_count,
        "posts": user_posts,
    })    

def index(request):
    all_posts = Post.objects.all().order_by("-created_at")
    
    return render(request, "network/index.html", {
        "posts": all_posts
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "network/register.html")

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/following.html
{% extends "network/layout.html" %}

{% block body %}

{% if users|length > 0 %}
{% for user in users %}

<div class="card">
  <div class="card-body d-flex justify-content-between">
    <div>
      <h3 class="card-title">{{ user.follow_from.username }}</h3>
    </div>

    {% if user.is_authenticated  %}
      <button class="btn btn-primary my-3">Follow</button>
    {% endif %}
  </div>
</div>


{% endfor %}
{% else %}

<em class="h4">No {{ page_type }} Found!</em>

{% endif %}


{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
    <h1>All Posts</h1>

    {% if user.is_authenticated %}
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">New Post</h3>
                
                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>

                    <script>
                      setTimeout(() => {
                        for (const elem of document.getElementsByClassName("alert")) {
                            elem.remove();
                        }
                      }, 1500)
                    </script>

                {% endfor %}
                
                <form method="POST" action="{% url 'create_post' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea required class="form-control" name="text" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Post</button>
                </form>
            </div>
        </div>
    {% endif %}

    {% include "network/post_list.html" %}
{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<link href="{% static 'network/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light px-4">
            <a class="navbar-brand" href="/">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile_page' user.username %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'following' username=user.username %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body px-4 p-2">
            {% block body %}
            {% endblock %}
        </div>
    </body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</html>

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/post_list.html
{% block content %}

    {% for post in posts %}
        <div class="card my-2">
          <div class="card-body">
            <div>
                <a href="{% url 'profile_page' post.author.username %}" class="h5 card-title">{{ post.author.username }}</a>
                <p class="text-muted">{{ post.created_at }}</p>
            </div>

            <p class="card-text"> {{ post.text }} </p>

            <div class="d-flex gap-2">
              <a href="{% url 'like' post.id %}" class="btn btn-link" style="--bs-btn-font-size: 1.05rem;">👍 Likes {{ post.like_set.all|length }}</a>

              {% if post.author.id == user.id %}
                <div class="btn btn-link fs-text-6" id="editButtons{{ post.id }}" style="--bs-btn-font-size: 1.05rem;" onclick="editPost(event, {{ post.id }})">✏️ Edit</div>
                <div class="btn btn-link fs-text-6" style="--bs-btn-font-size: 1.05rem; display: none;" id="saveButton{{ post.id }}" onclick="savePost(event, {{ post.id }})">💾 Save</div>
              {% endif %}

            </div>

          </div>
        </div>
    {% endfor  %}

    <script>
        function editPost(e, postId) {
            const cardBody = e.target.parentElement.parentElement.querySelector(".card-text");
            const textarea = document.createElement("textarea");

            document.getElementById(`editButtons${postId}`).style.display = "none";
            document.getElementById(`saveButton${postId}`).style.display = "block";

            e.target.removeEventListener("click", () => editPost(event, postId));
            document.getElementById(`saveButton${postId}`).addEventListener("click", () => savePost(event, postId));

            textarea.classList.add("form-control");
            textarea.value = cardBody?.innerText ?? "";
            cardBody?.parentNode?.replaceChild?.(textarea, cardBody);
        }

        function savePost(e, postId) {
            const cardParent = e.target.parentElement.parentElement;
            const cardBody = e.target.parentElement.parentElement.querySelector(".card-body");
            const textarea = e.target.parentElement.parentElement.querySelector("textarea");
            const newText = textarea.value;

            // Perform the fetch request to save the edited content
            fetch(`{% url 'edit_post' %}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                body: JSON.stringify({ text: newText, postId: postId }),
            })
            .then(response => {
                // Once the request is successful, update the UI and make the original edit button visible again

                const para = document.createElement("p")
                para.innerText = newText;
                para.classList.add("card-text")

                textarea.insertAdjacentElement("afterend", para)
                textarea.remove();

                document.getElementById(`editButtons${postId}`).style.display = "inline-block";
                document.getElementById(`saveButton${postId}`).style.display = "none";
                document.getElementById(`editButtons${postId}`).addEventListener("click", () => editPost(event, postId));
            })
            .catch(error => console.error('Error:', error));
        }
    </script>

{% endblock content %}

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block body %}

<div class="card">
  <div class="card-body d-flex justify-content-between">
    <div>

    <div class="d-flex align-items-center gap-2">
      <h3 class="card-title">{{ current_user.username }}</h3>
      <span class="text-muted">Joined: {{ current_user.date_joined }}</span>
    </div>

    <div class="d-flex gap-2">
      <a href="#" class="link">{{ followers_count }} Followers</a>
      <a href="#" class="link">{{ following_count }} Following</a>
    </div>
    </div>

    {% if user.is_authenticated and user.id != current_user.id %}

    <form action="{% url 'follow' %}" method="post" >
      {% csrf_token %}
      <input name="user_id" type="hidden" value="{{ current_user.id }}"/>
        {% if following %}
            <button type="submit" class="btn btn-secondary my-3">Unfollow</button>
        {% else %}
            <button type="submit" class="btn btn-primary my-3">Follow</button>
        {% endif %}
    </form>

    {% endif %}

  </div>
</div>

{% include "network/post_list.html" %}

{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project04_Network/network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}