Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("listing/<int:id>", views.view_listing, name="listing"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("add_comment", views.add_comment, name="add_comment"),
    path("close_auction", views.close_auction, name="close_auction"),
    path("place_bid", views.place_bid, name="place_bid")
]

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model

class User(AbstractUser):
    pass

class Base(models.Model):
    id = models.BigAutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

CATEGORIES = tuple((x, x.upper()) for x in ["Fashion", "None", "Toys", "Electronics", "Home"])
STATUS = tuple((x, x.upper()) for x in ["Closed", "Open", "Deleted"])

class Auction(Base):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image_url = models.URLField(blank=True)
    category  = models.CharField(max_length=32, choices=CATEGORIES, default="None", null=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=32, choices=STATUS, default="Open", null=True)

    def __str__(self):
        return self.title

class Bid(Base):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    bid_amount = models.DecimalField(max_digits=10, decimal_places=2)

class Comment(Base):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from .models import User, Auction, Bid, Comment

@login_required
def close_auction(request):
    if request.method == "POST":
        listing_id = request.POST.get("listing_id")
        listing = Auction.objects.get(id=listing_id)

        if request.user.id != listing.user.id:
            pass

        listing.status = "Closed"
        listing.save()

        return redirect(f"/listing/{listing_id}")
    else:
      return redirect("/")
    

@login_required
def place_bid(request):
    if request.method == "POST":
        bid_amount = request.POST.get("bid_amount")
        listing_id = request.POST.get("listing_id")

        listing = Auction.objects.get(id=listing_id)

        if not bid_amount or not listing_id:
            messages.error(request, "Invalid data sent")
        else:
            if int(bid_amount) <= int(listing.starting_bid):
                messages.error(request, f"Can't make a bid lower than ${listing.starting_bid}")
            else:
                Bid.objects.create(bid_amount=bid_amount, user=request.user, auction=listing)
                messages.info(request, "Successfully placed a bid")

        return redirect(f"/listing/{listing.id}")
    else:
      return redirect('index') 

def view_listing(request, id):
    found_listing = Auction.objects.get(id=id)
    found_bids = Bid.objects.filter(auction=found_listing).order_by("-bid_amount")
    found_comments = Comment.objects.filter(auction=found_listing)
    total_bids = len(found_bids)
    return render(request, "auctions/view_listing.html", {
        "listing": found_listing,
        "bids": found_bids,
        "total_bids": total_bids,
        "comments": found_comments
    })


def watchlist(request):
    return HttpResponse("This yo watchlist")

def create_listing(request):
    if request.method == "GET":
        return render(request, "auctions/create_listing.html")
    elif request.method == "POST":
        desc = request.POST.get("description")
        title = request.POST.get("title")
        cover_url = request.POST.get("cover_url")
        starting_bid = request.POST.get("starting_bid")

        Auction.objects.create(user_id=request.user.id, description=desc, title=title, image_url=cover_url, starting_bid=starting_bid)

        return redirect("index")


@login_required
def add_comment(request):
    user = request.user
    listing_id = request.POST.get("listing_id")
    auction = Auction.objects.get(id=listing_id)
    comment = request.POST.get("content")

    Comment.objects.create(user=user, text=comment, auction=auction)


    return redirect(request.META.get('HTTP_REFERER', None))
    

def index(request):
    active_listings = Auction.objects.filter(status="Open")
    closed_listings = Auction.objects.filter(status="Closed")

    active_listing_count = len(active_listings)
    closed_listing_count = len(closed_listings)

    return render(request, "auctions/index.html", {
        "active_listings": active_listings,
        "closed_listings": closed_listings,
        "active_listing_count": active_listing_count,
        "closed_listing_count": closed_listing_count,
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container mt-5">
    <form method="post" action="{% url 'create_listing' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title:</label>
            <input type="text" class="form-control" id="id_title" name="title" required>
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            <textarea class="form-control" id="id_description" name="description" rows="3" required></textarea>
        </div>
        <div class="form-group">
            <label for="id_starting_bid">Starting Bid:</label>
            <input type="number" class="form-control" id="id_starting_bid" name="starting_bid" step="0.01" required>
        </div>
        <div class="form-group">
            <label for="id_cover_url">Cover URL (optional):</label>
            <input type="url" class="form-control" id="id_cover_url" name="cover_url">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url 'index' %}" class="btn btn-secondary">Discard</a>
    </form>
</div>{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings ({{ active_listing_count }})</h2>

    <div class="card-deck">
      {% for listing in active_listings %}
      <div class="card col-sm-12 col-md-6">
        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap" style="width: 100%; object-fit: cover; height: 400px; object-position: top">
        <h5 class="card-header">{{ listing.title }}</h5>
        <div class="card-body">
          <h5 class="card-title">Starts at ${{ listing.starting_bid }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ listing.category }}</h6>
          <p class="card-text">{{ listing.description }}</p>
          <a href="/listing/{{ listing.id }}" class="btn btn-primary">View</a>
        </div>
      </div>
      {% endfor %}
    </div>

    <hr>

    <h2>Closed Auctions ( {{ closed_listing_count }} )</h2>

    <div class="card-deck" style="opacity: 60%; filter: grayscale(20);">
      {% for listing in closed_listings %}
      <div class="card col-sm-12 col-md-6">
        <img class="card-img-top" src="{{ listing.image_url }}" alt="Card image cap" style="width: 100%; object-fit: cover; height: 400px; object-position: top">
        <h5 class="card-header">{{ listing.title }}</h5>
        <div class="card-body">
          <h5 class="card-title">Started at ${{ listing.starting_bid }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ listing.category }}</h6>
          <p class="card-text">{{ listing.description }}</p>
          <p class="card-text">Auction Closed</p>
        </div>
      </div>
      {% endfor %}
    </div>
{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}


            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
            {% endif %}


        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

Web_Programming_With_Python_And_JavaScript/Project02_Commerce/auctions/templates/auctions/view_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-md-6">
            <div style="height: 400px; width: 100%">
                <img src="{{ listing.image_url }}" style="width: 100%; height: 100%; object-fit: contain" class="img-fluid" alt="Product Image">
            </div>
        </div>

        <div class="col-md-6">
            <h4>{{ listing.title }}</h4>
            <h1>${{ listing.starting_bid }}</h1> 

            {% if user.is_authenticated %}
            <form action="/place_bid" method="POST">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert" id="error-alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                    <script>
                        setTimeout(function(){
                            document.getElementById("error-alert").style.display = "none";
                        }, 1500);
                    </script>
                {% endif %}
                <div class="form-group">
                    <label for="bid">{{ total_bids }} bids so far</label>
                    <input type="number" name="bid_amount" class="form-control" id="bid" aria-describedby="Bid some amount" placeholder="Bid" {% if listing.status == "closed" %}disabled{% endif %}>
                    <input name="listing_id" type="hidden" value="{{ listing.id }}"/>
                </div>
                <button type="submit" class="btn btn-primary" {% if listing.status == "closed" %}disabled style="opacity: 0.5"{% endif %}>Place Bid</button>
            </form>           

            {% else %}
            <p>Sign in to place a bid</p>
            
            {% endif %}

            <h3>Details</h3>
            <ul>
                <li><b>Description:</b> {{ listing.description }}</li>
                <li><b>Listed by:</b>  {{ listing.user.username }}</li>
                <li><b>Category:</b> {{ listing.category }}</li>
                {% if listing.status == "Closed" %}
                    <li style="color: red; font-weight: bold;">Status: Closed</li>
                {% endif %}
            </ul>
        </div>

        <div class="col-12 col-md-6" style="margin-right: auto">
          <h2>Comments</h2>

          {% for comment in comments %}
          <div class="card mb-3">
            <div class="card-header">
              {{ comment.user.username }}
            </div>
            <div class="card-body">
              <p class="card-text">{{ comment.text }}</p>
            </div>
          </div>
          {% endfor %}

          <form method="post" action="{% url 'add_comment' %}">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_content">Comment:</label>
              <textarea class="form-control" id="id_content" name="content" rows="3" required></textarea>
            </div>
            <input type="hidden" name="listing_id" value="{{ listing.id }}">
            <button type="submit" class="btn btn-primary">Add Comment</button>
          </form>
        </div>

        <div class="col-12 col-md-6" style="margin-left: auto">


            <h2>Bids</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Bidder</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bid in bids %}
                    <tr>
                        <td>{{ bid.user.username }}</td>
                        <td>${{ bid.bid_amount }}</td>
                        <td>
                          <div class="btn-group">

                            {% if user.id == listing.user.id and listing.status != "Closed" %}
                            <form method="post" action="/close_auction">
                              {% csrf_token %}
                              <input type="hidden" name="listing_id" value="{{ listing.id }}">
                              <button type="submit" class="btn btn-secondary">Take and Close</button>
                            </form>
                            {% endif %}

                            {% if bid.user.id == user.id and listing.status != "Closed" %}
                                <button class="btn btn-danger">Delete</button>
                            {% endif %}

                            {% if listing.status == "Closed" %}
                                <button class="btn btn-secondary" disabled style="opacity: 0.5">Closed</button>
                            {% endif %}
                          </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock %}
<div